os: osx
osx_image: xcode11

script:
  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - ls Formula/*.rb
  - for formula in Formula/*.rb; do brew install ${formula}; done

notifications:
  email:
    on_success: never
    on_failure: always
