os: osx
osx_image: xcode11

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

script:
  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - ls Formula/*.rb
  - for formula in Formula/*.rb; do brew install ${formula} || (echo "Build failed."; exit 1); done

notifications:
  email:
    on_success: never
    on_failure: always
